GET http://localhost:3000/categories
Content-Type: application/json

###
GET http://localhost:3000/categories?filter=mov&per_page=2
Content-Type: application/json

###
GET http://localhost:3000/categories/db98bf0b-ef7e-4f93-962a-509a52079ffe
Content-Type: application/json

###
POST http://localhost:3000/categories
Content-Type: application/json

{
    "name": "some name"
}
###
PUT http://localhost:3000/categories/db98bf0b-ef7e-4f93-962a-509a52079ffe
Content-Type: application/json

{
    "name": "Movie"
}
###
DELETE http://localhost:3000/categories/db98bf0b-ef7e-4f93-962a-509a52079ffe
Content-Type: application/json

###